/* Generated by scripts/build-site.mjs. Add videos to portfolio/. */
window.PORTFOLIO_CATALOG = {
  "categories": {
    "AI": {
      "avatars": [
        "Аватары",
        "Avatars"
      ],
      "campaigns": [
        "Рекламные проекты",
        "Campaigns"
      ],
      "experiments": [
        "Эксперименты",
        "Experiments"
      ]
    },
    "Motion": {
      "commercials": [
        "Реклама",
        "Commercials"
      ],
      "product-3d": [
        "Продукт и 3D",
        "Product & 3D"
      ],
      "gambling": [
        "Гемблинг",
        "Gambling"
      ],
      "crypto": [
        "Крипта",
        "Crypto"
      ],
      "other": [
        "Другие работы",
        "Other projects"
      ]
    }
  },
  "projects": []
};
