import {readdir, readFile, stat} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';

export const categories = {
  AI: {
    avatars: ['Аватары', 'Avatars'],
    campaigns: ['Рекламные проекты', 'Campaigns'],
    experiments: ['Эксперименты', 'Experiments'],
  },
  Motion: {
    commercials: ['Реклама', 'Commercials'],
    'product-3d': ['Продукт и 3D', 'Product & 3D'],
    gambling: ['Гемблинг', 'Gambling'],
    crypto: ['Крипта', 'Crypto'],
    other: ['Другие работы', 'Other projects'],
  },
};

const url = relative => './portfolio/' + relative.split('/').map(encodeURIComponent).join('/');

async function walk(dir) {
  const entries = await readdir(dir, {withFileTypes: true}).catch(error => {
    if (error.code === 'ENOENT') return [];
    throw error;
  });
  const result = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name, 'en'))) {
    if (entry.name.startsWith('.') || entry.isSymbolicLink()) continue;
    const file = path.join(dir, entry.name);
    if (entry.isDirectory()) result.push(...await walk(file));
    else if (/\.(mp4|webm)$/i.test(entry.name)) result.push(file);
  }
  return result;
}

export async function scanPortfolio(root) {
  const projects = [];
  for (const section of Object.keys(categories)) {
    for (const file of await walk(path.join(root, section))) {
      const relative = path.relative(root, file).split(path.sep).join('/');
      const parts = relative.split('/');
      const category = parts.length > 2 ? parts[1] : 'other';
      const stem = file.slice(0, -path.extname(file).length);
      const title = path.basename(stem).replace(/[_-]+/g, ' ').trim();
      let metadata = {};
      try {
        metadata = JSON.parse(await readFile(stem + '.json', 'utf8'));
      } catch (error) {
        if (error.code !== 'ENOENT') throw new Error(`Invalid metadata for ${relative}: ${error.message}`);
      }
      if (!metadata || typeof metadata !== 'object' || Array.isArray(metadata)) {
        throw new Error(`Invalid metadata object: ${relative}`);
      }
      for (const key of ['title', 'description']) {
        const value = metadata[key];
        if (value !== undefined && !(typeof value === 'string' ||
          (value && typeof value === 'object' && !Array.isArray(value) && Object.values(value).every(v => typeof v === 'string')))) {
          throw new Error(`Invalid ${key}: ${relative}`);
        }
      }

      const size = (await stat(file)).size;
      if (size === 0) throw new Error(`Empty video: ${relative}`);
      let poster = null;
      for (const extension of ['jpg', 'jpeg', 'png', 'webp']) {
        const posterPath = stem + '.' + extension;
        if (await stat(posterPath).then(result => result.isFile()).catch(() => false)) {
          poster = url(path.relative(root, posterPath).split(path.sep).join('/'));
          break;
        }
      }
      if (!poster) throw new Error(`Missing poster for ${relative}. Run node scripts/generate-posters.mjs.`);

      const label = categories[section][category] || [category, category];
      projects.push({
        id: 'video-' + createHash('sha256').update(relative).digest('hex').slice(0, 16),
        number: String(projects.length + 1).padStart(2, '0'),
        section,
        category,
        categoryLabel: {ru: label[0], en: label[1]},
        copy: {title: metadata.title || title, description: metadata.description || ''},
        title,
        subtitle: section + ' / ' + label[0],
        description: '',
        video: url(relative),
        poster,
        color: section === 'AI' ? '#afa0e0' : '#67b9e6',
      });
    }
  }
  return {categories, projects};
}

export const serializeCatalog = catalog =>
  '/* Generated by scripts/build-site.mjs. Add videos to portfolio/. */\nwindow.PORTFOLIO_CATALOG = ' +
  JSON.stringify(catalog, null, 2).replace(/</g, '\\u003c') + ';\n';
